### ISSUE TITLE
External power supply socket in the original WT32-SC01 board

### ISSUE THREAD

**Issue by dizcza** [bsfconception/WT32-SC01#2]
Hi,
do you know the socket type used in the original WT32-SC01 (without an expansion board)?
It's denoted as J0 in the datasheet but it does not mention the socket plug type which can be soldered to J0 for easy battery connection.
![Screenshot from 2022-10-12 15-10-59](https://user-images.githubusercontent.com/7688337/195339713-5c939344-a131-4159-a189-a8250a13cfca.png)

**Comment by bsfconception** [comment]
Hi
I've not used neither verified but it could be a JST SH 1mm conector like
this one
https://fr.aliexpress.com/item/4001122058047.html
Regards

Le mer. 12 oct. 2022 à 14:14, Danylo Ulianych ***@***.***> a
écrit :

**Comment by dizcza** [comment]
Looks plausible. Thanks!

**Comment by dizcza** [comment]
I ordered the item you linked. The mounting pins (the bottom ones on the pic) fit perfectly with the JST SH 1mm connector but not the power pins (the upper ones). The power pins board spacing is ~1.5 mm while it should be 1.0 mm.

Don't know if it's a design flaw on their side or a Chinese feature.

Thanks anyway. I'll manually space the pins apart a bit further to fit onto the board.
